sudo: required
dist: trusty
language: python
python:
- '2.7'
- pypy
services:
  - docker
env:
  global:

before_install:
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine
